using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace FluxorBus.SourceGen;

/// <summary>
/// Generates source code to register message handler types for FluxorBus using incremental source generation.
/// </summary>
/// <remarks>This generator scans for classes annotated with the MessageHandlerAttribute that implement the
/// IMessageHandler<T/> interface, and produces extension methods to register these handlers with the dependency
/// injection container. The generated code simplifies the setup of message handlers in FluxorBus-based applications by
/// automating their registration. This generator is intended for use at compile time and does not affect runtime
/// behavior beyond code generation.</remarks>
#pragma warning disable RS1038 // Compiler extensions should be implemented in assemblies with compiler-provided references
#pragma warning disable RS1041 // Compiler extensions should be implemented in assemblies targeting netstandard2.0
[Generator]
#pragma warning restore RS1041 // Compiler extensions should be implemented in assemblies targeting netstandard2.0
#pragma warning restore RS1038 // Compiler extensions should be implemented in assemblies with compiler-provided references
public class FluxorBusGenerator : IIncrementalGenerator
{
    private const string MessageHandlerAttributeName = "FluxorBus.SourceGen.MessageHandlerAttribute";
    private const string InterfaceMessageHandlerName = "IMessageHandler";
    private const string InterfaceMessageHandlerFullName = "FluxorBus.Abstractions.IMessageHandler";

    /// <summary>
    /// Configures the incremental generator to process classes annotated with the message handler attribute and
    /// register the source output for code generation.
    /// </summary>
    /// <remarks>This method sets up the generator to discover classes with a specific attribute and ensures
    /// that code generation is triggered for each matching handler. It should be called during generator
    /// initialization.</remarks>
    /// <param name="context">The context used to configure the incremental generator and register source outputs.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                MessageHandlerAttributeName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(handlers, static (ctx, infos) => Execute(ctx, infos!));
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        var iface = symbol.AllInterfaces.FirstOrDefault(i => i is { Name: InterfaceMessageHandlerName, TypeArguments.Length: 1 });
        if (iface is null)
            return null;

        var messageType = iface.TypeArguments[0].ToDisplayString();
        var handlerType = symbol.ToDisplayString();

        return new HandlerInfo(handlerType, messageType);
    }

    private static void Execute(SourceProductionContext ctx, ImmutableArray<HandlerInfo> infos)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace FluxorBus.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class FluxorBusGeneratedExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddFluxorBusGenerated(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var info in infos)
        {
            sb.AppendLine($"        services.AddScoped(typeof({InterfaceMessageHandlerFullName}<{info.MessageType}>), typeof({info.HandlerType}));");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("FluxorBus.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record HandlerInfo(string HandlerType, string MessageType);
}